### ISSUE TITLE
Expired orders

### ISSUE THREAD

**Issue by shortthefomo** [XRPL-Labs/XRPL-Orderbook-Reader#12]
Looks like you're not taking into account expired orders here.

Had a read through the parser and did not see any checks on the expiration of the order.

Market Makers commonly use the expired field on their orders.

This will change the results of the data quite some.

**Comment by WietseWind** [comment]
That's a very good point! Yes, this will need addressing. 

The easiest way to implement this, is to use the existing logic for unfunded offers;
https://github.com/XRPL-Labs/XRPL-Orderbook-Reader/blob/master/src/parser/LiquidityParser.ts#L109

By simply saying: "if [expired](https://github.com/XRPLF/xrpl.js/blob/8b781479/packages/xrpl/src/utils/timeConversion.ts#L1_, unfunded amount equals offer amount" all existing logic will apply.

**Comment by lathanbritz** [comment]
```if ('Expiration' in offer && offer.Expiration < this.ledgerEpoch()) { continue }``` is what I do when iterating over the book orders.

**Comment by WietseWind** [comment]
Fixed & Published 0.4.0 :) Thank you!
